FROM node:20.1-alpine

ARG VITE_AUTH0_FRONTEND_CLIENT_ID
ARG VITE_AUTH0_FRONTEND_CLIENT_SECRET
ARG VITE_AUTH0_DOMAIN
ARG VITE_SERVER_ADDRESS
ARG VITE_SERVER_AUDIENCE
ENV VITE_AUTH0_FRONTEND_CLIENT_ID $VITE__AUTH0_FRONTEND_CLIENT_ID
ENV VITE_AUTH0_FRONTEND_CLIENT_SECRET $VITE__AUTH0_FRONTEND_CLIENT_SECRET
ENV VITE_AUTH0_DOMAIN $VITE_AUTH0_DOMAIN
ENV VITE_SERVER_ADDRESS $VITE_SERVER_ADDRESS
ENV VITE_SERVER_AUDIENCE $VITE_SERVER_AUDIENCE

WORKDIR /syncspace
COPY / /syncspace/
RUN npm install
RUN npm uninstall -g @ionic/cli
RUN npm install -g @ionic/cli@latest
CMD [ "ionic", "serve", "--no-livereload", "--host", "0.0.0.0" ]