FROM node:20.1-alpine

ARG REACT_APP_AUTH0_FRONTEND_CLIENT_ID
ARG REACT_APP_AUTH0_FRONTEND_CLIENT_SECRET
ARG REACT_APP_AUTH0_DOMAIN
ARG REACT_APP_SERVER_ADDRESS
ARG REACT_APP_SERVER_AUDIENCE
ENV REACT_APP_AUTH0_FRONTEND_CLIENT_ID $REACT_APP_AUTH0_FRONTEND_CLIENT_ID
ENV REACT_APP_AUTH0_FRONTEND_CLIENT_SECRET $REACT_APP_AUTH0_FRONTEND_CLIENT_SECRET
ENV REACT_APP_AUTH0_DOMAIN $REACT_APP_AUTH0_DOMAIN
ENV REACT_APP_SERVER_ADDRESS $REACT_APP_SERVER_ADDRESS
ENV REACT_APP_SERVER_AUDIENCE $REACT_APP_SERVER_AUDIENCE

WORKDIR /app
COPY / /app/
RUN npm install
RUN npm uninstall -g @ionic/cli
RUN npm install -g @ionic/cli@latest
CMD [ "ionic", "serve", "--no-livereload", "--host", "0.0.0.0" ]